### ISSUE TITLE
train data

### ISSUE THREAD

**Issue by Jack-bo1220** [jmoortgat/DeepRiverFCN#1]
A nice work!
could you share the link to the train data mentioned in your paper?
Thank you!

**Comment by jmoortgat** [comment]
Hi Jack-bo1220,
Thanks for your interest. It sounds like you are aware of the paper
accompanying this github project (
https://www.sciencedirect.com/science/article/pii/S0034425722003856).
I would love to share the training data, but unfortunately these involve
(labeled) commercial satellite imagery from the Maxar company, and their
licensing prohibits sharing of those data.
We have another paper in review that uses *super-resolution* FCN applied to
*free* Sentinel-2 imagery. Once that paper is accepted, we should be able
to share those training data, so please reach out again in a few months if
you're interested.
Best regards,
--Joachim

**Comment by Jack-bo1220** [comment]
Thank you for your quick reply! Sorry to bother you again by email.
And ss the data you plan to share after your other article is accepted from Sentinel-2?

**Comment by jmoortgat** [comment]
Thank you for the kind words, and my apologies for the extremely late reply — I wasn't monitoring this repository's issues at the time.

Unfortunately we cannot share the labeled training data: it is derived from commercial sub-meter WorldView imagery whose license does not permit redistribution. If you are a U.S. federally funded researcher, the underlying imagery is accessible through the Polar Geospatial Center (https://www.pgc.umn.edu/), and the labeling procedure is described in the paper (doi:10.1016/j.rse.2022.113279).

What we can offer are the trained model checkpoints for all five architectures (panchromatic and 4-band multispectral), which let you apply or fine-tune the models without our training set: see the link in checkpoints/README.md. The repository was also recently overhauled (working imports, modern TensorFlow support, pinned requirements), so a fresh clone should run out of the box.
